config/routes.rb
Rails.application.routes.draw do
  root to:'questions#index'
  resources :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    question = Question.create(
      body: params[:question][:body],
      user_id: params[:question][:user_id]
    )

    redirect_to question_path(question)
  end

  def update
    @question = Question.find(params[:id])
    @question.update(
      body: params[:question][:body],
      user_id: params[:question][:user_id]
    )
    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end
  
  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.all
    @question = Question.new
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question do |form| %>

  <h1 class="mt-md"> Question text </h1>

  <p> <%= form.text_area :body, rows:5, class: 'form_text_area'%> </p>

  <h1 class="mt-md"> <%= form.label :user_id%> </h1>

  <p> <%= form.text_field :user_id, class:'form_text_field'%> </p>

  <p class="mt-md"> <%= form.submit 'Save quesiton', class:  'button button-main'%> </p>
<% end %>

app/views/questions/_question.html.erb
<p class="mb-sm"><%= question.body %></p>
<div class="text-sm footer_question">
  <div class="text_grey">
    <%= l(question.created_at, format: :short) %>
  </div>

  <div>
    <%= link_to fa_icon('pencil'), edit_question_path(question), title: 'Update question' %>
    <%= button_to fa_icon('trash-o'), question_path(question), method: :delete, title: 'Delete question' %>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h1 class="title-lg mb-md">Update question <%= @question.id %></h1>

  <%= render 'form', question:@question %>

</div>

app/views/questions/index.html.erb
<div class="container">

  <p class="mt-md">
    <%=render 'form', question:@question %>
  </p>
</div>

  <div class="container mt-sm">
    <h2 class="title-lg">All questions</h2>
  </div>

  <% @questions.each do |question| %>
    <div class="container mt-sm">
      <%= render question%>
    </div>
  <%end%>
  <p class="mt-md">
    <%= link_to "Create new question", new_question_path, class:  'button button-main' %>
  </p>

app/views/questions/new.html.erb
<div class="container">

  <h1 class="title-lg mb-md">Create question</h1>

  <%= render 'form', question:@question %>

</div>

app/views/questions/show.html.erb
<div class="container">
  <%= render 'question', question:@question %>
  <p class="mt-md"><%= link_to "All question", questions_path %></p>
</div>